### ISSUE TITLE
Different result between this repo and OCELoT for lan-bridge submission of ru-sah.

### ISSUE THREAD

**Issue by BrightXiaoHan** [wmt-conference/wmt22-news-systems#1]
Hi. 
Our Team Name： Lan-Bridge
On the OCELoT, our bleu score is 15.3.
<img width="1157" alt="截屏2022-08-26 07 46 03" src="https://user-images.githubusercontent.com/25839309/186788002-92884a35-8799-4fbf-aab2-e9d26842bb78.png">
But the result in this repo is only 0.016. And I'm sure I choose the right submission.
<img width="918" alt="截屏2022-08-26 07 48 46" src="https://user-images.githubusercontent.com/25839309/186788232-11d2e321-bdd9-41c8-828e-7f2d4c4d4b8b.png">

**Comment by kocmitom** [comment]
Hello, the export is done by automatic script taking only primary systems, therefore the problem is not going to be there.
But we had a bug in Livonian and Yakut testsets, thus OCELoT has miscalculated scores. Therefore for those languages, the OCELoT results are not correct and the scores in the repo are correct.

But based on repo scores, your output seems to be broken. Anyway, the data are from Submission 682, which is identical to the TXT file you have submitted (I double checked):
https://github.com/wmt-conference/wmt22-news-systems/blob/main/txt/system-outputs/generaltest2022.ru-sah.hyp.Lan-Bridge.sah
(you should be able to double check that the lines match).

But the sentence order of your submission is not matching sources we asked to be translated: https://www.statmt.org/wmt22/wmttest2022.src.zip

I am not sure what happened, it is a pity you have not submitted XML where at least sentence ID would be visible. But looking at your outputs, it doesn't seem to be a problem with shuffled sentences as average length of your outputs is significantly longer than average for references.
